import type { ClientDefinition } from "@/types/tenant";

/** Fallback when ChannelAdmin has no blog settings saved yet. */
export const DEFAULT_BLOG_SETTINGS: Omit<
  ClientDefinition,
  "clientName" | "label"
> = {
  publicPath: "/blog",
  brand: {
    name: "Blog",
    alternateName: "blog",
    tagline: "Blogs worth reading.",
    description: "Latest articles and updates.",
    author: "Editorial",
    logo: "",
    locale: "en_US",
    language: "en-US",
  },
  copy: {
    heroEyebrow: "Editorial",
    heroTitle: "Latest blogs",
    heroSubtitle: "Product updates, guides, and notes from the field.",
    heroCta: "Browse blogs",
    storiesEyebrow: "Latest",
    storiesHeading: "Latest blogs",
    storiesDescription: "Fresh reads from the editorial desk.",
    footerTagline: "Clarity over clutter.",
    notFoundTitle: "This blog isn’t here",
    notFoundMessage:
      "The page may have moved, or the slug doesn’t match a published post.",
    notFoundCta: "Back to home",
    emptyTitle: "No blogs yet",
    emptyMessage: "Publish a blog for this website in ChannelAdmin",
  },
  seo: {
    keywords: [],
  },
  pageSeo: {
    title: "",
    description: "",
    metaTitle: "",
    metaDescription: "",
    metaKeywords: "",
    focusKeyword: "",
    openGraphTitle: "",
    openGraphDescription: "",
    openGraphImageUrl: "",
    openGraphType: "website",
    twitterCardTitle: "",
    twitterCardDescription: "",
    twitterCardImageUrl: "",
    twitterCardType: "summary_large_image",
    category: "",
    faqItems: [],
    schemaMarkup: "",
    noindex: false,
    nofollow: false,
  },
  nav: [{ label: "Blogs", href: "/#blogs" }],
  footerGroups: [],
  social: {},
  footerContact: {
    addressLines: [],
    email: "",
    phone: "",
    hours: [],
  },
  categories: [],
  tags: [],
  authors: [{ slug: "editorial", name: "Editorial" }],
  sections: {
    featured: false,
    categories: false,
    newsletter: false,
  },
  theme: {
    id: "default",
    tokens: {},
    heroLayout: "split",
    customCss: "",
  },
};
